-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d")SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE 1=1
AND SALES_DATE like "2022-03%"

UNION ALL 

SELECT SALES_DATE, PRODUCT_ID ,NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE 1=1
AND SALES_DATE like "2022-03%"
ORDER BY 1,2,3