-- 코드를 입력하세요
# 리뷰 평균 점수 소수점 세번째 자리 반올림
# 서울 식당 ID, 이름, 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
# 평균점수 내림차순, 즐겨찾기 내림차순
SELECT
A.REST_ID,
A.REST_NAME,
A.FOOD_TYPE,
A.FAVORITES,
A.ADDRESS,
# B.REVIEW_SCORE AS SCORE
FORMAT(ROUND(SUM(B.REVIEW_SCORE)/COUNT(A.REST_ID), 3),2) AS SCORE
# FORMAT(ROUND((SELECT SUM(B.REVIEW_SCORE)/COUNT(A.REST_ID)
# FROM REST_INFO AS A JOIN REST_REVIEW AS B ON A.REST_ID=B.REST_ID), 3),2) AS SCORE
FROM REST_INFO AS A JOIN REST_REVIEW AS B ON A.REST_ID=B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC