WITH GENDER_INFO_Y AS (
    SELECT USER_ID
         , GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)

SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , UI.GENDER AS GENDER
     , COUNT(DISTINCT UI.USER_ID) AS USERS
FROM GENDER_INFO_Y AS UI
    INNER JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR
       , MONTH
       , GENDER
ORDER BY YEAR
       , MONTH
       , GENDER