SELECT
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS MP
JOIN
    REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE
    MP.MEMBER_ID = (
        SELECT
            MP.MEMBER_ID
        FROM
            MEMBER_PROFILE AS MP
        JOIN
            REST_REVIEW AS RR ON MP.MEMBER_ID = RR.MEMBER_ID
        GROUP BY
            MP.MEMBER_ID
        ORDER BY
            COUNT(*) DESC
        LIMIT 1
    )
ORDER BY
    RR.REVIEW_DATE, RR.REVIEW_TEXT;
