-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK RIGHT JOIN AUTHOR ON BOOK.AUTHOR_ID=AUTHOR.AUTHOR_ID
-- FROM BOOK, AUTHOR
WHERE BOOK.CATEGORY LIKE '%경제%'
ORDER BY BOOK.PUBLISHED_DATE