-- 코드를 입력하세요
SELECT
A.CATEGORY,
A.PRICE,
A.PRODUCT_NAME
FROM FOOD_PRODUCT AS A JOIN (
    SELECT CATEGORY,
    MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY
) AS B
ON A.CATEGORY=B.CATEGORY AND A.PRICE=B.MAX_PRICE
ORDER BY PRICE DESC;

# SELECT
# a.CATEGORY,
# a.PRICE,
# a.PRODUCT_NAME
# FROM FOOD_PRODUCT a JOIN (
#     SELECT CATEGORY, MAX(PRICE) MAX_PRICE
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
#     GROUP BY CATEGORY
# ) b
# ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX_PRICE
# ORDER BY PRICE DESC;